### ISSUE TITLE
Benchmarks, brief explanation and different data set sizes.

### ISSUE THREAD

**Issue by joshuapinter** [Aaron-Bird/ivy#1]
First off, this is friggin' cool!

I would love to see three things here: 

1. Benchmarks to compare how long each method takes.

2. A brief explanation of what each method is doing and how they differ (maybe strengths/weaknesses).

3. Easily change the dataset size from 10 to 100, to maybe 1,000 or 10,000.

So cool! Great job! 👏 👏

**Comment by Aaron-Bird** [comment]
Thank you so much for your suggestion!
I will consider adding these features.
